### ISSUE TITLE
Facebook events integration

### ISSUE THREAD

**Issue by vircung** [HackerspaceLBN/Obsidian#5]
There is need for process to  integrate Facebook Events into Obsidian
- [ ] fetch events from Hackerspace/Mackerspace fanpage
- [ ] update events based on linked Facebook event
- [ ] rake job to perform fetch/update

**Comment by sptq** [comment]
I think this gem is good for this job: https://github.com/nov/fb_graph 

I don't have any experience of this gem but I was creating the same functionality in php.

**Comment by vircung** [comment]
That's great. Please go ahead.

But please remember about opening PR. We will try to follow git flow and https://github.com/flow

Best regards
Jacek Nakonieczny

-----Wiadomość oryginalna-----
Od: "Marcin Grochulski" <notifications@github.com>
Wysłano: ‎2015-‎07-‎05 19:13
Do: "HackerspaceLBN/Obsidian" <Obsidian@noreply.github.com>
DW: "Jacek Nakonieczny" <jacek.nakonieczny@gmail.com>
Temat: Re: [Obsidian] Facebook events integration (#5)

I think this gem is good for this job: https://github.com/nov/fb_graph 
I don't have any experience of this gem but I was creating the same functionality in php.

**Comment by vircung** [comment]
Sorry that's proper link  https://guides.github.com/introduction/flow/index.html

Best regards
Jacek Nakonieczny

-----Wiadomość oryginalna-----
Od: "Marcin Grochulski" <notifications@github.com>
Wysłano: ‎2015-‎07-‎05 19:13
Do: "HackerspaceLBN/Obsidian" <Obsidian@noreply.github.com>
DW: "Jacek Nakonieczny" <jacek.nakonieczny@gmail.com>
Temat: Re: [Obsidian] Facebook events integration (#5)

I think this gem is good for this job: https://github.com/nov/fb_graph 
I don't have any experience of this gem but I was creating the same functionality in php.
